module.exports = {
	'tasktype' : {
		'-1' : 'CHECK_TASK',
		'1' : 'activate-scientific',
		'11' : 'sythonix',
		'12' : 'sythonix product',
		'13' : 'sythonix msds',
		'21' : 'arkpharminc',
		'22' : 'arkpharminc product',
		'23' : 'arkpharminc msds',
		'31' : 'alfachina',
		'32' : 'alfachina product',
		'33' : 'alfachina msds',
		'41' : 'tcichemicals',
		'42' : 'tcichemicals product',
		'43' : 'tcichemicals msds',
		'51' : 'sigmaaldrich',
		'52' : 'sigmaaldrich product',
		'53' : 'sigmaaldrich msds',
		'61' : 'acros',
		'62' : 'acros product',
		'63' : 'acros msds',
		'71' : 'Guide common',
		'74' : 'Guide msds',
		'81' : 'chemcas common',
		'84' : 'chemcas msds',
		'91' : 'energy chemical common',
		'92' : 'energy chemical product',
		'101' : 'adamas beta common',
		'102' : 'adamas beta product',
		'111'  : 'aladdin-e',
		'121'  : 'shao-yuan',
		'131'  : 'biderpharmatech',
		'141'  : 'bepharm',
		'10001' : 'CAS extract'
	}
};
